### ISSUE TITLE
crash - `gsub': incompatible encoding regexp match

### ISSUE THREAD

**Issue by roipoussiere** [apjanke/ronn-ng#54] opened 2020-07-18 22:22 UTC
After a fresh ronn install with `apt install ronn` (Ronn-NG v0.8.0) on Kubuntu 20.04, I get this error:

```
ronn --roff --pipe ./doc/amethyst_man.md > ./build/report/amethyst.1
Traceback (most recent call last):
        23: from /usr/bin/ronn:184:in `<main>'
        22: from /usr/bin/ronn:184:in `each'
        21: from /usr/bin/ronn:199:in `block in <main>'
        20: from /usr/bin/ronn:199:in `each'
        19: from /usr/bin/ronn:220:in `block (2 levels) in <main>'
        18: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:240:in `convert'
        17: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `to_roff'
        16: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `new'
        15: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:18:in `initialize'
        14: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:91:in `block_filter'
        13: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block_filter'
        12: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
        11: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
        10: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
         9: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block in block_filter'
         8: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:120:in `block_filter'
         7: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `inline_filter'
         6: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
         5: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
         4: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
         3: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `block in inline_filter'
         2: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:247:in `inline_filter'
         1: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `write'
/usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `gsub': incompatible encoding regexp match (Windows-31J regexp with UTF-8 string) (Encoding::CompatibilityError)
```

**Comment by nabijaczleweli** [comment] 2020-07-18 22:28
This was fixed in 0.9.0-1: https://tracker.debian.org/news/1116879/accepted-ruby-ronn-090-1exp1-source-into-experimental/. Contact your distributors for an up-to-date package.

**Comment by roipoussiere** [comment] 2020-07-19 08:54
> Contact your distributors for an up-to-date package.

Ok, never did it, I reported it [here](https://bugs.launchpad.net/ubuntu/+source/ruby-ronn/+bug/1888114), I hope it's the right place.

**Comment by apjanke** [comment] 2020-07-19 18:40
Yikes! I'll have a look at this ASAP. Thank you for the bug report.

**Comment by apjanke** [comment] 2020-07-19 18:46
Okay, I think what's going on is that this has already been fixed here in Ronn-NG, but Ubuntu specifically might be using an old version of Ronn (possibly from before my Ronn-NG fork happened), and we need to see if they'll update to Ronn-NG 0.9.x if they haven't already.

Looking at the Ubuntu Ronn package definition here – https://packages.ubuntu.com/search?keywords=ronn – it looks like Ubuntu 20.04 was still using the old Ronn 0.8.0, and they are switching to my Ronn-NG 0.9 in the upcoming Ubuntu groovuy release. So I think you might be out of luck until the new version of Ubuntu comes out, but it will be fixed before too long.

If you really need a fix now, you could manually install Ronn-NG 0.9.1 into your `/usr/local` directory, overriding the old `ronn` provided by the system through `apt`.

**Comment by apjanke** [comment] 2020-07-19 18:56
I suppose if I were feeling really brave, I could go back and try to reproduce an 0.8.2 patch release with this bugfix, and see if Ubuntu 20.x would pull it in.

**Comment by apjanke** [comment] 2020-07-19 19:01
Your analysis here looks right to me.

> As for getting a normal-priority bug for a zero-priority package into an Ubuntu LTS: I admire your optimism.

LOL, point taken. :)

**Comment by apjanke** [comment] 2020-09-11 23:19
I'm afraid this is a downstream packaging issue that is out of my control: Like @nabijaczleweli says, I don't think Ubuntu LTS is going to take a patch release for Ronn 0.8.x here.

I recommend that you either install 0.9.1-1 deb as @nabijaczleweli suggests, or install Ronn 0.9 from source into your /usr/local/.

Closing as downstream/already-fixed, since I don't think there's anything else for me to do here.

Thanks for the report regardless!

**Closed by apjanke** 2020-09-11 23:19 UTC
Labels: bug, packaging
