### ISSUE TITLE
Rendering acute accent instead of apostrophe

### ISSUE THREAD

**Issue by sergiosacj** [apjanke/ronn-ng#66] opened 2020-12-21 21:33 UTC
Some packages in Debian have this [lintian report](https://lintian.debian.org/tags/acute-accent-in-manual-page.html) on rendering acute accent instead of apostrophe. This look like a bug in Roon-NG.

Testing file:
```
manpage(1) -- My manpage
============================================

## DESCRIPTION

This won't generate an apostrophe.
```

ronn invocation:
```
$ ronn --roff < test.md > test.1
```

Manual output:
```
.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "MANPAGE" "1" "December 2020" ""
.SH "NAME"
\fBmanpage\fR \- My manpage
.SH "DESCRIPTION"
This won\'t generate an apostrophe\.
```

It looks like \\' should be '.

**Comment by apjanke** [comment] 2020-12-21 21:55
Thanks for the bug report!

I think we've already fixed this one in #55 and #58 and it's just waiting for a new release to roll out. Can you try the reproduction test with the latest code from `master` and see if the output looks good to you now?

**Comment by sergiosacj** [comment] 2020-12-21 23:37
I used the latest code and it worked as needed, thanks for your work and help!

**Comment by apjanke** [comment] 2020-12-22 00:02
Great! Closing as duplicate of #55; please subscribe to that issue if you'd like further progress updates.

**Closed by apjanke** 2020-12-22 00:02 UTC
Labels: bug
