### ISSUE TITLE
Manpages generated via --pipe don't have .TH macro

### ISSUE THREAD

**Issue by adminspotter** [apjanke/ronn-ng#29] opened 2019-08-08 14:36 UTC
It seems like the *only* method for getting a complete manpage is for ronn to pull the manpage title and section (first two elements of the `.TH` roff macro) from the filename, e.g. foo.3.md will be the `FOO.3.MD` manpage from section '3'.  If the page is processed as a pipe, the `.TH` element is completely missing.  There are no command-line flags to inject those two elements into the process, so any manpages processed in this way are incomplete.

Also, ronn uses the full filename as the page title, including the section number and `.md` extension.  It's able to pull the section number out properly, but drops any parsing for the page title.  A quick test with filename `input.3.md`:

```plain
.\" generated with Ronn-NG/v0.8.2
.\" http://github.com/apjanke/ronn-ng/tree/0.8.2
.TH "INPUT\.3\.MD" "3" "August 2019" "Testing" "Testing Manual"
.SH "NAME"
Testing \- a test of ronn
.SH "SYNOPSIS"
test stuff
.SH "DESCRIPTION"
This is a test manpage for testing out ronn\.
.SH "RELATED"
Nothing\.
```

That title ought to be "INPUT", rather than the full filename.  If we drop the `.md` extension and call the file `input.3`, we get a proper title, but no longer any section number:

```
.TH "INPUT" "" "August 2019" "Testing" "Testing Manual"
```

I guess what I'm suggesting with all of this is a couple new command-line flags, `--title` and `--section`, both to allow ronn to function as a pipe, and also to ease the behaviours around its sensing of those parameters.

All this was done with the latest release:
```plain
$ ronn --version
Ronn-NG v0.8.2
http://github.com/apjanke/ronn-ng/tree/0.8.2
```

**Comment by adminspotter** [comment] 2019-08-08 16:32
I think I mostly just answered my own question, on digging into the code - `--name` and `--section` exist and do seem to work fine, but they are undocumented in the usage text.

See pull request #30 :)

**Comment by apjanke** [comment] 2019-08-15 18:56
Sorry for the slow response; I didn't have "Follow" turned on for this repo, so I wasn't getting notifications of new issues.

I agree with your analysis here.

Merged #30.

Sounds like we now need to a) fix the file name parsing to strip the "<section>.md" from the filenames to correct the section title, and b) get the `.TH` macros to show up in `--pipe` output, right?

**Comment by adminspotter** [comment] 2019-08-16 03:54
Once I discovered the `--name` and `--section` CLOs, `--pipe` output is working just groovy.  So no bug there.  I think it makes sense that if all of the options for the manpage aren't present that no `.TH` macro should be generated.

My ruby is darned rusty, but I can give fixing up the filename parsing a shot.

**Comment by apjanke** [comment] 2019-08-16 04:12
> Once I discovered the --name and --section CLOs, --pipe output is working just groovy. So no bug there. I think it makes sense that if all of the options for the manpage aren't present that no .TH macro should be generated.

Excellent.

> My ruby is darned rusty, but I can give fixing up the filename parsing a shot.

I think I got it done: https://github.com/apjanke/ronn-ng/commit/7ecf61daa42672a5bfe9bebe4cc9429e321d6830. Can you test and see if it works for you too?

The issue is that it was only stripping `.ronn` extensions, instead of arbitrary extensions like `.md`.

**Comment by adminspotter** [comment] 2019-08-16 06:07
Seems like the change is working:
```plain
$ ../../ronn-ng/bin/ronn --roff foo.3.md 
     roff: ./foo.3                                    
warning: file `<standard input>', around line 47:
  table wider than line width
$ grep ^\.TH foo.3
.TH "FOO" "3" "August 2019" "" ""
$ cp foo.3.md foo.3.ronn
$ ../../ronn-ng/bin/ronn --roff foo.3.ronn
     roff: ./foo.3                                    
warning: file `<standard input>', around line 47:
  table wider than line width
$ grep ^\.TH foo.3
.TH "FOO" "3" "August 2019" "" ""
```

**Comment by apjanke** [comment] 2019-08-16 06:16
Perfect.

Marking this as closed since I think we're all done here, right?

**Closed by apjanke** 2019-08-16 06:16 UTC
Labels: bug

**Comment by adminspotter** [comment] 2019-08-16 06:40
That's everything I had, so closed seems a good state. :)

Keep up the great work!

**Comment by apjanke** [comment] 2019-08-16 06:50
Thanks!
